export const products = [
  {
    id: 1,
    name: "Nem Nắm Truyền Thống",
    price: 50000,
    originalPrice: 55000,
    image: "/nem-nam-01.png",
    rating: 4.9,
    reviews: 156,
    description: "Nem nắm được làm từ thịt heo tươi, ủ chua theo công thức truyền thống, gói lá chuối thơm ngon",
    badge: "Đặc sản",
    unit: "kg",
    stock: 50,
    category: "Nem Nắm",
  },
  {
    id: 2,
    name: "Bột Sắn Nguyên Chất",
    price: 145000,
    originalPrice: 155000,
    image: "/bot-san-04.png",
    rating: 4.8,
    reviews: 203,
    description: "Bột sắn được sấy khô tự nhiên, không chất bảo quản, thích hợp làm bánh và các món ăn",
    badge: "Sạch",
    unit: "kg",
    stock: 100,
    category: "Bột Sắn",
  },
  {
    id: 3,
    name: "Bột Nghệ Tươi",
    price: 125000,
    originalPrice: 135000,
    image: "/bot-nghe-01.png",
    rating: 4.7,
    reviews: 124,
    description: "Nghệ tươi được sấy khô và xay mịn, giữ nguyên màu sắc và dưỡng chất tự nhiên",
    badge: "Organic",
    unit: "kg",
    stock: 75,
    category: "Bột Nghệ",
  },
  {
    id: 4,
    name: "Combo 2 Sản Phẩm",
    price: 260000,
    originalPrice: 270000,
    image: "/bot-san.png",
    rating: 4.9,
    reviews: 89,
    description: "Combo gồm bột sắn (1kg), bột nghệ (0.5kg) - tiết kiệm hơn khi mua lẻ",
    badge: "Tiết kiệm",
    unit: "combo",
    stock: 30,
    category: "Combo",
  },
  {
    id: 5,
    name: "Bột Sắn Đóng Gói 500g",
    price: 75000,
    originalPrice: 78000,
    image: "/bot-san-03.png",
    rating: 4.8,
    reviews: 78,
    description: "Bột sắn nguyên chất đóng gói nhỏ, tiện lợi sử dụng",
    badge: "Mới",
    unit: "gói",
    stock: 120,
    category: "Bột Sắn",
  },
]