export const products = [
  {
    id: 1,
    name: "Bột Sắn Nguyên Chất",
    price: 150000,
    originalPrice: 170000,
    image: "/bot-san.jpg",
    weight: "1kg",
    rating: 4.8,
    reviews: 203,
    description: "Bột sắn được sấy khô tự nhiên, không chất bảo quản, thích hợp làm bánh và các món ăn",
    badge: "Sạch",
    unit: "kg",
    stock: 100,
    category: "Bột Sắn",
  },
  {
    id: 2,
    name: "Tinh Bột Nghệ Tươi",
    price: 140000,
    originalPrice: 160000,
    image: "/bot-nghe.jpg",
    rating: 4.7,
    weight: "1kg",
    reviews: 124,
    description: "Nghệ tươi được sấy khô và xay mịn, giữ nguyên màu sắc và dưỡng chất tự nhiên",
    badge: "Organic",
    unit: "kg",
    stock: 75,
    category: "Bột Nghệ",
  },
  {
    id: 3,
    name: "Combo 2 Sản Phẩm",
    price: 285000,
    originalPrice: 330000,
    weight: "1kg/mỗi sp",
    image: "/combo-01.jpg",
    rating: 4.9,
    reviews: 89,
    description: "Combo gồm bột sắn (1kg), bột nghệ (1kg) - tiết kiệm hơn khi mua lẻ",
    badge: "Tiết kiệm",
    unit: "combo",
    stock: 30,
    category: "Combo",
  },
  {
    id: 4,
    name: "Bột Hoàng Thanh Nguyên Chất",
    price: 1200000,
    originalPrice: 1300000,
    image: "/bot-hoang-thanh-02.webp",
    rating: 5,
    weight: "1kg",
    reviews: 78,
    description: "Bột hoàng thanh nguyên chất đóng gói, tiện lợi sử dụng",
    badge: "Mới",
    unit: "gói",
    stock: 120,
    category: "Bột Hoàng Thanh",
  },
]

export const categories = [
  {
    id: 1,
    name: "Bột Sắn",
    image: "/bot-san-01.png",
    description: "Bột sắn nguyên chất, không chất bảo quản",
  },
  {
    id: 2,
    name: "Bột Nghệ",
    image: "/bot-nghe.jpg",
    description: "Bột nghệ tươi xay mịn, giữ nguyên dưỡng chất",
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Nguyễn Văn Huy",
    avatar: "/placeholder.svg?height=50&width=50",
    comment: "Sản phẩm rất chất lượng, đóng gói cẩn thận. Nem nắm thơm ngon như ở quê làm, sẽ ủng hộ shop dài dài.",
    rating: 5,
  },
  {
    id: 2,
    name: "Trần Thị Hồng",
    avatar: "/placeholder.svg?height=50&width=50",
    comment: "Bột sắn rất mịn và trắng, làm bánh rất ngon. Giao hàng nhanh, sẽ mua lại.",
    rating: 5,
  },
  {
    id: 3,
    name: "Lê Văn Nghị",
    avatar: "/placeholder.svg?height=50&width=50",
    comment: "Bột nghệ thơm, màu đẹp. Đã mua nhiều lần và luôn hài lòng với chất lượng.",
    rating: 4,
  },
]